pipeline {
    agent any
    
    parameters {
        choice(name: 'TESTING_TYPE',  choices: ['api','e2e'], description: 'Enter testing type that you want to execute')
        choice(name: 'BROWSER', choices: ['chrome','firefox'], description: 'Choice the browser where you want to execute your scripts')
    }
    
    options {
        ansiColor('xterm')
    }
     
    stages {
        stage('Building'){
            steps{
                echo "Building the application"
            }
        }
        stage('Testing'){
            steps{
                bat "npm i"
                bat "npx cypress run --browser ${BROWSER} --config-file=./cypress/${TESTING_TYPE}/cypress.config.ts --reporter mochawesome"
                bat "npm run cy-merge-reports"
                bat "npm run cy-mochawesome-report"
            }
        }
        stage('Deploying'){
            steps{
                echo 'Deploy the application'
            }
        }
}
}